apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: immigration-messages
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: immigration-messages
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: immigration-messages
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: tputbrese.azurecr.io/tap1.6-apps-live-update:latest?sub_path=/
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/debug-convention
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: tputbrese.azurecr.io/tap1.6-apps-live-update:latest@sha256:be212a1b8614d87b8eb8dab4c836a9c327731066dae2d2529f7cadbe9dc6f403
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: immigration-messages
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: immigration-messages
    spec:
      containers:
      - env:
        - name: SECRET_KEY_BASE
          value: some-secret-key-base
        - name: BPL_DEBUG_ENABLED
          value: "true"
        - name: BPL_DEBUG_PORT
          value: "9005"
        image: tputbrese.azurecr.io/tap1.7-apps/immigration-messages-sandbox-1-ns@sha256:4780adfbc83e90ec4c8bf2dad149706fe725356edf65ba0afde6f4ecc2f980e7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

