apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: immigration-messages-postgresql-rails-7-demo
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: immigration-messages
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: immigration-messages
spec:
  name: postgresql-rails-7-demo
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: postgresql-rails-7-demo
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: immigration-messages
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: immigration-messages-redis-rails-7-demo
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: immigration-messages
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: immigration-messages
spec:
  name: redis-rails-7-demo
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: redis-rails-7-demo
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: immigration-messages

